title: "Geo-AUV"
logo: ./content/assets/UNIS_logo.gif
author: Peter Betlem, Nil Rodes, Sara M. Cohen
copyright: "2023 (CC-BY-NC except where otherwise stated)"

repository:
  url: https://github.com/UNISvalbard/Geo-AUV

html:
  use_issues_button: true
  use_repository_button: false
  extra_navbar: ""
  use_edit_page_button: true
  announcement: 'Found this tutorial helpful? Please participate in the survey (<a href="https://unisvalbard.github.io/AG222/content/survey.html">click here</a>) & Star me!        <iframe src="https://ghbtns.com/github-btn.html?user=UNISvalbard&repo=AG222&type=star&count=true" frameborder="0" scrolling="0" width="150" height="20" title="GitHub"></iframe>'
  home_page_in_navbar: Sign up for the <a href="https://www.unis.no/course/ag-222-integrated-geological-methods-from-outcrop-to-geomodel/">UNIS AG222 course</a>

launch_buttons:
  binderhub_url: ""

execute:
  execute_notebooks: "auto"

parse:
  myst_extended_syntax: true
  myst_header_anchors: 4

sphinx:
  config:
    #bibtex_reference_style: author_year
    bibtex_default_style: plain

only_build_toc_files: true